#!/usr/bin/env node

import assert from "node:assert/strict";
import { Buffer } from "node:buffer";
import { existsSync, readFileSync } from "node:fs";
import { test } from "vitest";

import {
  appFile,
  assertTypeChecks,
  copyfromUsageFile,
  copyfromValidationFile,
  flushAsync,
  loadCopyfromTestHelpers,
  loadGeneratedModule,
  postgresDriverTemplateFile,
  postgresGeneratedFiles,
  printTsNodes,
  relativePath,
  ts,
} from "../test-support/driver-test-helpers.mjs";

test("generated postgres copyfrom queries use COPY stream helpers", () => {
  for (const generatedFile of postgresGeneratedFiles) {
    assert.ok(
      existsSync(generatedFile),
      `Missing generated postgres output: ${generatedFile}`
    );

    const source = readFileSync(generatedFile, "utf8");

    assert.match(
      source,
      /-- name: CopyAuthors :copyfrom\b/,
      `${relativePath(generatedFile)} must include a generated :copyfrom example.`
    );
    assert.match(
      source,
      /export async function copyAuthors\(sql: Sql \| TransactionSql, args: CopyAuthorsArgs\[\]\)/,
      `${relativePath(generatedFile)} must accept transaction-capable COPY clients.`
    );
    assert.match(
      source,
      /interface SqlcCopyFromWritable/,
      `${relativePath(generatedFile)} must emit a minimal COPY writable stream interface.`
    );
    assert.match(
      source,
      /COPY \\\"authors\\\" \(\\\"name\\\", \\\"bio\\\"\) FROM STDIN/,
      `${relativePath(generatedFile)} must generate a COPY FROM STDIN statement.`
    );
    assert.match(
      source,
      /sqlcCopyFromValue/,
      `${relativePath(generatedFile)} must emit COPY text escaping helpers.`
    );
    assert.match(
      source,
      /sqlcCopyFromBytea/,
      `${relativePath(generatedFile)} must emit bytea COPY encoding helpers.`
    );
    assert.match(
      source,
      /sqlcCopyFromJson/,
      `${relativePath(generatedFile)} must emit json COPY encoding helpers.`
    );
    assert.match(
      source,
      /sqlcCopyFromArrayEncoder/,
      `${relativePath(generatedFile)} must emit PostgreSQL array COPY encoding helpers.`
    );
    assert.match(
      source,
      /sqlcCopyFromUnsupportedValue/,
      `${relativePath(generatedFile)} must reject unsupported COPY value types instead of stringifying them.`
    );
    assert.match(
      source,
      /sqlcCopyFromDrain/,
      `${relativePath(generatedFile)} must wait for COPY write backpressure drain events.`
    );
    assert.match(
      source,
      /stream\.once\?\.\("error"/,
      `${relativePath(generatedFile)} must listen for COPY stream finalization errors.`
    );
    assert.match(
      source,
      /\.writable\(\)/,
      `${relativePath(generatedFile)} must use the postgres.js COPY writable stream.`
    );
  }
});

test("generated postgres copyfrom output type-checks with strict noUncheckedIndexedAccess", () => {
  assertTypeChecks("Generated postgres copyfrom output", [
    ...postgresGeneratedFiles,
    copyfromUsageFile,
  ]);
});

test("postgres copyfrom generator template uses COPY streams", () => {
  const source = readFileSync(postgresDriverTemplateFile, "utf8");
  assert.match(
    source,
    /function copyfromSupportDecls\(\): Node\[\]/,
    "postgres driver must generate shared copyfrom support."
  );
  assert.match(
    source,
    /interface SqlcCopyFromWritable/,
    "postgres driver must generate a minimal COPY writable interface."
  );
  assert.match(
    source,
    /\.writable\(\)/,
    "postgres driver must generate postgres.js COPY writable usage."
  );
  assert.match(
    source,
    /export async function \$\{funcName\}\(sql: Sql \| TransactionSql/,
    "postgres driver must type COPY clients as Sql or TransactionSql."
  );
  assert.match(
    source,
    /COPY \$\{copyfromTableName\(table\)\}/,
    "postgres driver must build COPY SQL from sqlc insert metadata."
  );
  assert.match(
    source,
    /sqlcCopyFromBytea/,
    "postgres driver must encode generated bytea Buffer/Uint8Array values."
  );
  assert.match(
    source,
    /sqlcCopyFromJson/,
    "postgres driver must encode generated json/jsonb values."
  );
  assert.match(
    source,
    /sqlcCopyFromArrayEncoder/,
    "postgres driver must encode generated PostgreSQL array values."
  );
  assert.match(
    source,
    /sqlcCopyFromUnsupportedValue/,
    "postgres driver must reject unsupported COPY value types instead of stringifying them."
  );
  assert.match(
    source,
    /sqlcCopyFromDrain/,
    "postgres driver must wait for COPY write backpressure drain events."
  );
  assert.match(
    source,
    /copyRowBatch/,
    "postgres driver must batch COPY rows before writing to the stream."
  );
  assert.match(
    source,
    /stream\.once\?\.\("error"/,
    "postgres driver must listen for COPY stream finalization errors."
  );
});

function copyfromQuery(text, params = 2) {
  return {
    text,
    name: "CopyAuthors",
    cmd: ":copyfrom",
    columns: [],
    params: Array.from({ length: params }, (_, index) => ({ number: index + 1 })),
    comments: [],
    filename: "query.sql",
    insertIntoTable: { name: "authors", schema: "" },
  };
}

test("copyfrom validation accepts only simple insert value lists", () => {
  const { validateCopyfromQuery } = loadGeneratedModule(copyfromValidationFile);

  assert.doesNotThrow(() =>
    validateCopyfromQuery(copyfromQuery(`
      INSERT INTO authors (
        name, bio
      ) VALUES (
        $1, $2
      );
    `))
  );
  assert.doesNotThrow(() =>
    validateCopyfromQuery(copyfromQuery(`INSERT INTO "authors" ("na)me", bio) VALUES ($1, $2);`))
  );

  for (const sql of [
    `WITH rows AS (SELECT $1) INSERT INTO authors (name, bio) VALUES ($1, $2)`,
    `INSERT INTO authors (name, bio) VALUES ($1, DEFAULT)`,
    `INSERT INTO authors (name, bio) VALUES ($1, lower($2))`,
    `INSERT INTO authors (name, bio) VALUES ($1, 'constant')`,
    `INSERT INTO authors (name, bio) VALUES ($1, $2) RETURNING *`,
    `INSERT INTO authors (name, bio) VALUES ($1, $2) ON CONFLICT DO NOTHING`,
    `INSERT INTO authors (name, bio) VALUES ($1, $2), ($3, $4)`,
  ]) {
    assert.throws(
      () => validateCopyfromQuery(copyfromQuery(sql)),
      /:copyfrom query CopyAuthors must be a simple INSERT INTO table \(columns\.\.\.\) VALUES \(\$1, \.\.\.\) statement/
    );
  }

  assert.throws(
    () =>
      validateCopyfromQuery({
        ...copyfromQuery(`INSERT INTO books (name, bio) VALUES ($1, $2)`),
        insertIntoTable: { name: "authors", schema: "" },
      }),
    /INSERT table must match sqlc table metadata/
  );
});

test("app validates copyfrom query shapes before generating COPY", () => {
  const source = readFileSync(appFile, "utf8");
  assert.match(source, /import \{ validateCopyfromQuery \} from "\.\/copyfrom-validation";/);
  assert.match(source, /case ":copyfrom": \{\n\s+validateCopyfromQuery\(query\);/);
});

test("postgres copyfrom codegen selects encoders from column metadata", () => {
  const { Driver } = loadGeneratedModule(postgresDriverTemplateFile, {
    typescript: ts,
    "../gen/plugin/codegen_pb": {},
    "./utlis": {
      argName(index, column) {
        return column?.name ?? `arg${index + 1}`;
      },
      colName(index, column) {
        return column?.name ?? `col${index + 1}`;
      },
    },
    "../logger": { log() {} },
  });
  const params = [
    { number: 1, column: { name: "payload", originalName: "payload", type: { name: "bytea" } } },
    { number: 2, column: { name: "doc", originalName: "doc", type: { name: "json" } } },
    { number: 3, column: { name: "docb", originalName: "docb", type: { name: "jsonb" } } },
    { number: 4, column: { name: "tags", originalName: "tags", type: { name: "text" }, isArray: true } },
  ];
  const source = printTsNodes(
    new Driver().copyfromDecl(
      "copyMixed",
      "copyMixedQuery",
      "CopyMixedArgs",
      params,
      { name: "mixed", schema: "" }
    )
  );

  assert.match(
    source,
    /const copyEncoders: SqlcCopyFromEncoder\[\] = \[sqlcCopyFromBytea, sqlcCopyFromJson, sqlcCopyFromJson, sqlcCopyFromArrayEncoder\(sqlcCopyFromScalar, 1\)\];/
  );
  assert.match(
    source,
    /sqlcCopyFromRow\(\[arg\.payload, arg\.doc, arg\.docb, arg\.tags\], copyEncoders\)/
  );
});

test("generated postgres copyfrom function streams escaped COPY text", async () => {
  const { copyAuthors } = loadGeneratedModule(
    postgresGeneratedFiles[0],
    { postgres: { Sql: class Sql {} } }
  );
  const chunks = [];
  let copyQuery;
  let ended = false;
  const writable = {
    write(chunk, callback) {
      chunks.push(String(chunk));
      callback();
    },
    end(callback) {
      ended = true;
      callback();
    },
  };
  const sql = {
    unsafe(query) {
      copyQuery = query;
      return {
        writable() {
          return Promise.resolve(writable);
        },
      };
    },
  };

  const date = new Date("2024-01-02T03:04:05.006Z");
  const count = await copyAuthors(sql, [
    { name: "Ann\tA", bio: null },
    { name: "Back\\slash", bio: "line\nnext" },
    { name: "carriage\rreturn", bio: "literal\\N" },
    { name: "Dated", bio: date },
  ]);

  assert.equal(count, 4);
  assert.equal(ended, true);
  assert.equal(copyQuery, 'COPY "authors" ("name", "bio") FROM STDIN');
  assert.equal(
    chunks.join(""),
    "Ann\\tA\t\\N\nBack\\\\slash\tline\\nnext\ncarriage\\rreturn\tliteral\\\\N\nDated\t2024-01-02T03:04:05.006Z\n"
  );
  assert.equal(chunks.length, 1, "small COPY inputs should be batched into one stream write.");
});

test("postgres copyfrom helpers encode bytea json and arrays", () => {
  const helpers = loadCopyfromTestHelpers();

  assert.equal(
    helpers.sqlcCopyFromValue(Buffer.from([0, 15, 255]), helpers.sqlcCopyFromBytea),
    "\\\\x000fff"
  );
  assert.equal(
    helpers.sqlcCopyFromValue(new Uint8Array([1, 2, 16]), helpers.sqlcCopyFromBytea),
    "\\\\x010210"
  );
  assert.equal(
    helpers.sqlcCopyFromValue({ a: 1, b: ["x", true] }, helpers.sqlcCopyFromJson),
    '{"a":1,"b":["x",true]}'
  );
  assert.equal(
    helpers.sqlcCopyFromValue([1, "two"], helpers.sqlcCopyFromJson),
    '[1,"two"]'
  );

  const textArrayEncoder = helpers.sqlcCopyFromArrayEncoder(helpers.sqlcCopyFromScalar, 1);
  assert.equal(
    helpers.sqlcCopyFromValue(["a", "b,c", 'quote"', "back\\slash", null], textArrayEncoder),
    '{"a","b,c","quote\\\\"","back\\\\\\\\slash",NULL}'
  );

  const numberMatrixEncoder = helpers.sqlcCopyFromArrayEncoder(helpers.sqlcCopyFromScalar, 2);
  assert.equal(
    helpers.sqlcCopyFromValue([[1, 2], [3, null]], numberMatrixEncoder),
    '{{"1","2"},{"3",NULL}}'
  );
});

class FailingCopyWritable {
  constructor(error) {
    this.error = error;
    this.writableFinished = false;
    this.chunks = [];
    this.listeners = new Map();
    this.destroyedWith = undefined;
  }

  write(chunk, callback) {
    this.chunks.push(String(chunk));
    callback();
  }

  end(callback) {
    callback();
    queueMicrotask(() => this.listeners.get("error")?.(this.error));
  }

  once(event, listener) {
    this.listeners.set(event, listener);
    return this;
  }

  off(event, listener) {
    if (this.listeners.get(event) === listener) {
      this.listeners.delete(event);
    }
    return this;
  }

  removeListener(event, listener) {
    return this.off(event, listener);
  }

  destroy(error) {
    this.destroyedWith = error;
  }
}

test("generated postgres copyfrom function rejects final COPY stream failures", async () => {
  const { copyAuthors } = loadGeneratedModule(
    postgresGeneratedFiles[0],
    { postgres: { Sql: class Sql {} } }
  );
  const failure = new Error("COPY finalization failed");
  const writable = new FailingCopyWritable(failure);
  const sql = {
    unsafe() {
      return {
        writable() {
          return Promise.resolve(writable);
        },
      };
    },
  };

  await assert.rejects(
    copyAuthors(sql, [{ name: "Ann", bio: null }]),
    (error) => {
      assert.equal(error, failure);
      assert.equal(writable.destroyedWith, failure);
      return true;
    }
  );
  assert.equal(writable.chunks.join(""), "Ann\t\\N\n");
});

test("generated postgres copyfrom function resolves callback-only evented streams", async () => {
  const { copyAuthors } = loadGeneratedModule(
    postgresGeneratedFiles[0],
    { postgres: { Sql: class Sql {} } }
  );
  const chunks = [];
  const writable = {
    writableFinished: false,
    write(chunk, callback) {
      chunks.push(String(chunk));
      callback();
    },
    end(callback) {
      this.writableFinished = true;
      callback();
    },
    once() {
      return this;
    },
    off() {
      return this;
    },
    removeListener() {
      return this;
    },
  };
  const sql = {
    unsafe() {
      return {
        writable() {
          return Promise.resolve(writable);
        },
      };
    },
  };

  assert.equal(await copyAuthors(sql, [{ name: "Ann", bio: null }]), 1);
  assert.equal(chunks.join(""), "Ann\t\\N\n");
});

test("generated postgres copyfrom function rejects premature stream close", async () => {
  const { copyAuthors } = loadGeneratedModule(
    postgresGeneratedFiles[0],
    { postgres: { Sql: class Sql {} } }
  );
  const listeners = new Map();
  let destroyedWith;
  const writable = {
    writableFinished: false,
    write(_chunk, callback) {
      callback();
    },
    end(callback) {
      callback();
      queueMicrotask(() => listeners.get("close")?.());
    },
    once(event, listener) {
      listeners.set(event, listener);
      return this;
    },
    off(event, listener) {
      if (listeners.get(event) === listener) {
        listeners.delete(event);
      }
      return this;
    },
    removeListener(event, listener) {
      return this.off(event, listener);
    },
    destroy(error) {
      destroyedWith = error;
    },
  };
  const sql = {
    unsafe() {
      return {
        writable() {
          return Promise.resolve(writable);
        },
      };
    },
  };

  await assert.rejects(
    copyAuthors(sql, [{ name: "Ann", bio: null }]),
    (error) => {
      assert.match(error.message, /COPY stream closed before finish/);
      assert.equal(destroyedWith, error);
      return true;
    }
  );
});

test("generated postgres copyfrom function waits for write backpressure", async () => {
  const { copyAuthors } = loadGeneratedModule(
    postgresGeneratedFiles[0],
    { postgres: { Sql: class Sql {} } }
  );
  const listeners = new Map();
  const writeCallbacks = [];
  const chunks = [];
  let ended = false;
  const writable = {
    write(chunk, callback) {
      chunks.push(String(chunk));
      writeCallbacks.push(callback);
      return false;
    },
    end(callback) {
      ended = true;
      callback();
    },
    once(event, listener) {
      listeners.set(event, listener);
      return this;
    },
    off(event, listener) {
      if (listeners.get(event) === listener) {
        listeners.delete(event);
      }
      return this;
    },
    removeListener(event, listener) {
      return this.off(event, listener);
    },
  };
  const sql = {
    unsafe() {
      return {
        writable() {
          return Promise.resolve(writable);
        },
      };
    },
  };

  const result = copyAuthors(sql, [{ name: "Ann", bio: null }]);
  await flushAsync();
  assert.equal(chunks.length, 1);
  assert.equal(ended, false, "COPY must not end until the backpressured write drains.");

  writeCallbacks[0]();
  listeners.get("drain")?.();
  assert.equal(await result, 1);
  assert.equal(ended, true);
});

test("generated postgres copyfrom function rejects write callback errors before end", async () => {
  const { copyAuthors } = loadGeneratedModule(
    postgresGeneratedFiles[0],
    { postgres: { Sql: class Sql {} } }
  );
  const failure = new Error("write failed");
  let ended = false;
  let destroyedWith;
  const writable = {
    write(_chunk, callback) {
      queueMicrotask(() => callback(failure));
      return true;
    },
    end(callback) {
      ended = true;
      callback();
    },
    destroy(error) {
      destroyedWith = error;
    },
  };
  const sql = {
    unsafe() {
      return {
        writable() {
          return Promise.resolve(writable);
        },
      };
    },
  };

  await assert.rejects(copyAuthors(sql, [{ name: "Ann", bio: null }]), (error) => {
    assert.equal(error, failure);
    assert.equal(destroyedWith, failure);
    return true;
  });
  assert.equal(ended, false, "COPY must not finalize after a write callback fails.");
});

test("generated postgres copyfrom function rejects backpressured callback errors without events", async () => {
  const { copyAuthors } = loadGeneratedModule(
    postgresGeneratedFiles[0],
    { postgres: { Sql: class Sql {} } }
  );
  const failure = new Error("backpressured write failed");
  let ended = false;
  let destroyedWith;
  const writable = {
    write(_chunk, callback) {
      queueMicrotask(() => callback(failure));
      return false;
    },
    end(callback) {
      ended = true;
      callback();
    },
    destroy(error) {
      destroyedWith = error;
    },
  };
  const sql = {
    unsafe() {
      return {
        writable() {
          return Promise.resolve(writable);
        },
      };
    },
  };

  await assert.rejects(copyAuthors(sql, [{ name: "Ann", bio: null }]), (error) => {
    assert.equal(error, failure);
    assert.equal(destroyedWith, failure);
    return true;
  });
  assert.equal(ended, false, "COPY must not hang or finalize after a backpressured write callback fails.");
});

test("generated postgres copyfrom function rejects unsupported value types", async () => {
  const { copyAuthors } = loadGeneratedModule(
    postgresGeneratedFiles[0],
    { postgres: { Sql: class Sql {} } }
  );

  for (const unsupportedValue of [
    { first: "Ann" },
    ["Ann"],
    Buffer.from("Ann"),
  ]) {
    const chunks = [];
    let destroyedWith;
    const writable = {
      write(chunk, callback) {
        chunks.push(String(chunk));
        callback();
      },
      end(callback) {
        callback();
      },
      destroy(error) {
        destroyedWith = error;
      },
    };
    const sql = {
      unsafe() {
        return {
          writable() {
            return Promise.resolve(writable);
          },
        };
      },
    };

    await assert.rejects(
      copyAuthors(sql, [{ name: unsupportedValue, bio: null }]),
      (error) => {
        assert.ok(error instanceof TypeError);
        assert.match(error.message, /scalar columns/);
        assert.equal(destroyedWith, error);
        return true;
      }
    );
    assert.equal(chunks.length, 0);
  }
});
