// Code generated by sqlc. DO NOT EDIT.

import type { Sql, TransactionSql } from "postgres";

type SqlcCopyFromEvent = "error" | "finish" | "close" | "drain";
type SqlcCopyFromListener = (error?: unknown) => void;
type SqlcCopyFromEncoder = (value: unknown) => string;

const sqlcCopyFromMaxChunkBytes = 65536;

interface SqlcCopyFromWritable {
    write(chunk: string, callback: (error?: Error | null) => void): boolean;
    end(callback: (error?: Error | null) => void): void;
    destroy?(error?: unknown): void;
    readonly writableFinished?: boolean;
    once?(event: SqlcCopyFromEvent, listener: SqlcCopyFromListener): SqlcCopyFromWritable;
    off?(event: SqlcCopyFromEvent, listener: SqlcCopyFromListener): SqlcCopyFromWritable;
    removeListener?(event: SqlcCopyFromEvent, listener: SqlcCopyFromListener): SqlcCopyFromWritable;
}

interface SqlcCopyFromQueuedWrite {
    canContinue: boolean;
    complete: Promise<void>;
    failed: Promise<void>;
}

interface SqlcCopyFromState {
    error?: Error;
    pendingWrites: Promise<void>[];
}

function sqlcCopyFromCreateState(): SqlcCopyFromState {
    return { pendingWrites: [] };
}

function sqlcCopyFromError(error: unknown): Error {
    return error instanceof Error ? error : new Error(String(error ?? "COPY stream failed"));
}

function sqlcCopyFromRecordError(state: SqlcCopyFromState, error: unknown): void {
    state.error ??= sqlcCopyFromError(error);
}

function sqlcCopyFromThrowIfError(state: SqlcCopyFromState): void {
    if (state.error) {
        throw state.error;
    }
}

function sqlcCopyFromUnsupportedValue(value: unknown, expected = "null, string, number, boolean, bigint, Date, Uint8Array/Buffer, JSON-serializable values, and arrays for PostgreSQL array columns"): TypeError {
    const tag = Object.prototype.toString.call(value);
    return new TypeError(":copyfrom supports only " + expected + "; received " + tag);
}

function sqlcCopyFromScalar(value: unknown): string {
    switch (typeof value) {
        case "string":
            return value;
        case "number":
            return String(value);
        case "boolean":
            return value ? "true" : "false";
        case "bigint":
            return value.toString();
        case "object":
            if (value instanceof Date) {
                return value.toISOString();
            }
            throw sqlcCopyFromUnsupportedValue(value, "string, number, boolean, bigint, and Date values for scalar columns");
        default:
            throw sqlcCopyFromUnsupportedValue(value, "string, number, boolean, bigint, and Date values for scalar columns");
    }
}

function sqlcCopyFromBytea(value: unknown): string {
    let bytes: Uint8Array | undefined;
    if (typeof ArrayBuffer !== "undefined") {
        if (ArrayBuffer.isView(value)) {
            const view = value as ArrayBufferView;
            bytes = new Uint8Array(view.buffer, view.byteOffset, view.byteLength);
        } else if (value instanceof ArrayBuffer || Object.prototype.toString.call(value) === "[object ArrayBuffer]") {
            bytes = new Uint8Array(value as ArrayBuffer);
        }
    }
    if (!bytes) {
        throw sqlcCopyFromUnsupportedValue(value, "Uint8Array or Buffer values for bytea columns");
    }

    let hex = "";
    for (let index = 0; index < bytes.length; index++) {
        const byte = bytes[index];
        if (byte === undefined) {
            continue;
        }
        hex += byte.toString(16).padStart(2, "0");
    }
    return "\\x" + hex;
}

function sqlcCopyFromJson(value: unknown): string {
    let text: string | undefined;
    try {
        text = JSON.stringify(value);
    } catch {
        throw sqlcCopyFromUnsupportedValue(value, "JSON-serializable values for json/jsonb columns");
    }
    if (text === undefined) {
        throw sqlcCopyFromUnsupportedValue(value, "JSON-serializable values for json/jsonb columns");
    }
    return text;
}

function sqlcCopyFromArrayEncoder(elementEncoder: SqlcCopyFromEncoder, dimensions: number): SqlcCopyFromEncoder {
    return (value: unknown) => sqlcCopyFromArray(value, elementEncoder, dimensions);
}

function sqlcCopyFromArray(value: unknown, elementEncoder: SqlcCopyFromEncoder, dimensions: number): string {
    if (!Array.isArray(value)) {
        throw sqlcCopyFromUnsupportedValue(value, "arrays for PostgreSQL array columns");
    }
    const nestedDimensions = dimensions - 1;
    return "{" + value.map((element) => {
        if (element === null || element === undefined) {
            return "NULL";
        }
        if (nestedDimensions > 0) {
            return sqlcCopyFromArray(element, elementEncoder, nestedDimensions);
        }
        return sqlcCopyFromArrayElement(elementEncoder(element));
    }).join(",") + "}";
}

function sqlcCopyFromArrayElement(value: string): string {
    return '"' + value.replace(/\\/g, "\\\\").replace(/"/g, "\\\"") + '"';
}

function sqlcCopyFromValue(value: unknown, encoder: SqlcCopyFromEncoder): string {
    if (value === null || value === undefined) {
        return "\\N";
    }
    return encoder(value)
        .replace(/\\/g, "\\\\")
        .replace(/\t/g, "\\t")
        .replace(/\n/g, "\\n")
        .replace(/\r/g, "\\r");
}

function sqlcCopyFromRow(values: unknown[], encoders: SqlcCopyFromEncoder[]): string {
    if (values.length !== encoders.length) {
        throw new Error(":copyfrom row has " + values.length + " values, expected " + encoders.length);
    }
    return values.map((value, index) => {
        const encoder = encoders[index];
        if (!encoder) {
            throw new Error(":copyfrom row is missing encoder for column " + index);
        }
        return sqlcCopyFromValue(value, encoder);
    }).join("\t") + "\n";
}

function sqlcCopyFromQueueWrite(stream: SqlcCopyFromWritable, state: SqlcCopyFromState, chunk: string): SqlcCopyFromQueuedWrite {
    let canContinue = true;
    let notifyFailed!: () => void;
    const failed = new Promise<void>((resolve) => {
        notifyFailed = resolve;
    });
    const complete = new Promise<void>((resolve) => {
        const finish = (error?: unknown) => {
            if (error) {
                sqlcCopyFromRecordError(state, error);
                notifyFailed();
            }
            resolve();
        };
        try {
            canContinue = stream.write(chunk, (error?: Error | null) => finish(error ?? undefined)) !== false;
        } catch (error) {
            canContinue = false;
            finish(error);
        }
    });
    state.pendingWrites.push(complete);
    return { canContinue, complete, failed };
}

async function sqlcCopyFromWrite(stream: SqlcCopyFromWritable, state: SqlcCopyFromState, chunk: string): Promise<void> {
    if (chunk.length === 0) {
        return;
    }
    sqlcCopyFromThrowIfError(state);
    const queuedWrite = sqlcCopyFromQueueWrite(stream, state, chunk);
    sqlcCopyFromThrowIfError(state);
    if (!queuedWrite.canContinue) {
        await sqlcCopyFromDrain(stream, state, queuedWrite);
    }
    sqlcCopyFromThrowIfError(state);
}

async function sqlcCopyFromDrain(stream: SqlcCopyFromWritable, state: SqlcCopyFromState, queuedWrite: SqlcCopyFromQueuedWrite): Promise<void> {
    if (typeof stream.once !== "function") {
        await queuedWrite.complete;
        sqlcCopyFromThrowIfError(state);
        return;
    }
    await Promise.race([
        queuedWrite.failed.then(() => sqlcCopyFromThrowIfError(state)),
        new Promise<void>((resolve, reject) => {
        let settled = false;
        const cleanup = () => {
            stream.off?.("drain", onDrain) ?? stream.removeListener?.("drain", onDrain);
            stream.off?.("error", onError) ?? stream.removeListener?.("error", onError);
            stream.off?.("close", onClose) ?? stream.removeListener?.("close", onClose);
        };
        const settle = (complete: () => void) => {
            if (settled) {
                return;
            }
            settled = true;
            cleanup();
            complete();
        };
        const onDrain = () => settle(() => resolve());
        const onError = (error?: unknown) => settle(() => {
            sqlcCopyFromRecordError(state, error);
            reject(state.error);
        });
        const onClose = () => {
            if (stream.writableFinished === true) {
                onDrain();
                return;
            }
            onError(new Error("COPY stream closed before drain"));
        };
        stream.once?.("drain", onDrain);
        stream.once?.("error", onError);
        stream.once?.("close", onClose);
        }),
    ]);
    sqlcCopyFromThrowIfError(state);
}

async function sqlcCopyFromFlushWrites(state: SqlcCopyFromState): Promise<void> {
    while (state.pendingWrites.length > 0) {
        const pendingWrites = state.pendingWrites;
        state.pendingWrites = [];
        await Promise.all(pendingWrites);
    }
    sqlcCopyFromThrowIfError(state);
}

async function sqlcCopyFromEnd(stream: SqlcCopyFromWritable): Promise<void> {
    await new Promise<void>((resolve, reject) => {
        let settled = false;
        const hasCompletionEvents = typeof stream.once === "function";
        const cleanup = () => {
            stream.off?.("error", onError) ?? stream.removeListener?.("error", onError);
            stream.off?.("finish", onFinish) ?? stream.removeListener?.("finish", onFinish);
            stream.off?.("close", onClose) ?? stream.removeListener?.("close", onClose);
        };
        const settle = (complete: () => void) => {
            if (settled) {
                return;
            }
            settled = true;
            cleanup();
            complete();
        };
        const onError = (error?: unknown) => settle(() => reject(sqlcCopyFromError(error)));
        const onFinish = () => settle(() => resolve());
        const onClose = () => {
            if (stream.writableFinished === true) {
                onFinish();
                return;
            }
            onError(new Error("COPY stream closed before finish"));
        };

        if (hasCompletionEvents) {
            stream.once?.("error", onError);
            stream.once?.("finish", onFinish);
            stream.once?.("close", onClose);
        }

        stream.end((error?: Error | null) => {
            if (error) {
                onError(error);
                return;
            }
            if (!hasCompletionEvents || stream.writableFinished !== false) {
                onFinish();
            }
        });
    });
}


/**
 * Options for generated batch queries.
 * batchSize bounds pipelined queries per reserved connection chunk; chunks run in input order.
 */
export interface SqlcBatchOptions {
    batchSize?: number;
}

export interface SqlcBatchErrorItem {
    index: number;
    error: unknown;
}

/**
 * Batch functions reject with this after the first failed chunk.
 * errors contain input indexes; later chunks are not started.
 */
export class SqlcBatchError extends Error {
    readonly errors: SqlcBatchErrorItem[];

    constructor(errors: SqlcBatchErrorItem[]) {
        super(`Batch failed for ${errors.length} item(s)`);
        this.name = "SqlcBatchError";
        this.errors = errors;
    }
}

function sqlcBatchSize(options: SqlcBatchOptions | undefined): number {
    const batchSize = options?.batchSize ?? 64;
    if (!Number.isInteger(batchSize) || batchSize < 1) {
        throw new RangeError("batchSize must be a positive integer");
    }
    return batchSize;
}

async function sqlcRunBatched<TArg, TResult>(
    args: TArg[],
    options: SqlcBatchOptions | undefined,
    run: (arg: TArg, index: number) => Promise<TResult>
): Promise<TResult[]> {
    const batchSize = sqlcBatchSize(options);
    const results = new Array<TResult>(args.length);
    for (let start = 0; start < args.length; start += batchSize) {
        const chunk = args.slice(start, start + batchSize);
        const settled = await Promise.allSettled(chunk.map((arg, offset) => run(arg, start + offset)));
        const errors: SqlcBatchErrorItem[] = [];
        for (const [offset, result] of settled.entries()) {
            const index = start + offset;
            if (result.status === "fulfilled") {
                results[index] = result.value;
            } else {
                errors.push({ index, error: result.reason });
            }
        }
        if (errors.length > 0) {
            throw new SqlcBatchError(errors);
        }
    }
    return results;
}


export const getAuthorQuery = `-- name: GetAuthor :one
SELECT id, name, bio FROM authors
WHERE id = $1 LIMIT 1`;

export interface GetAuthorArgs {
    id: string;
}

export interface GetAuthorRow {
    id: string;
    name: string;
    bio: string | null;
}

export async function getAuthor(sql: Sql | TransactionSql, args: GetAuthorArgs): Promise<GetAuthorRow | null> {
    const rows = await sql.unsafe(getAuthorQuery, [args.id]).values();
    if (rows.length !== 1) {
        return null;
    }
    const row = rows[0];
    if (!row) {
        return null;
    }
    return {
        id: row[0],
        name: row[1],
        bio: row[2]
    };
}

export const listAuthorsQuery = `-- name: ListAuthors :many
SELECT id, name, bio FROM authors
ORDER BY name`;

export interface ListAuthorsRow {
    id: string;
    name: string;
    bio: string | null;
}

export async function listAuthors(sql: Sql | TransactionSql): Promise<ListAuthorsRow[]> {
    return (await sql.unsafe(listAuthorsQuery, []).values()).map(row => ({
        id: row[0],
        name: row[1],
        bio: row[2]
    }));
}

export const createAuthorQuery = `-- name: CreateAuthor :one
INSERT INTO authors (
  name, bio
) VALUES (
  $1, $2
)
RETURNING id, name, bio`;

export interface CreateAuthorArgs {
    name: string;
    bio: string | null;
}

export interface CreateAuthorRow {
    id: string;
    name: string;
    bio: string | null;
}

export async function createAuthor(sql: Sql | TransactionSql, args: CreateAuthorArgs): Promise<CreateAuthorRow | null> {
    const rows = await sql.unsafe(createAuthorQuery, [args.name, args.bio]).values();
    if (rows.length !== 1) {
        return null;
    }
    const row = rows[0];
    if (!row) {
        return null;
    }
    return {
        id: row[0],
        name: row[1],
        bio: row[2]
    };
}

export const copyAuthorsQuery = `-- name: CopyAuthors :copyfrom
INSERT INTO authors (
  name, bio
) VALUES (
  $1, $2
)`;

export interface CopyAuthorsArgs {
    name: string;
    bio: string | null;
}

export async function copyAuthors(sql: Sql | TransactionSql, args: CopyAuthorsArgs[]): Promise<number> {
    const copyStream = await sql.unsafe("COPY \"authors\" (\"name\", \"bio\") FROM STDIN").writable() as SqlcCopyFromWritable;
    const copyStreamState = sqlcCopyFromCreateState();
    const copyEncoders: SqlcCopyFromEncoder[] = [sqlcCopyFromScalar, sqlcCopyFromScalar];
    const onCopyStreamError = (error?: unknown) => {
        sqlcCopyFromRecordError(copyStreamState, error);
    };
    copyStream.once?.("error", onCopyStreamError);
    try {
        let copyRowBatch = "";
        for (const arg of args) {
            sqlcCopyFromThrowIfError(copyStreamState);
            const copyRow = sqlcCopyFromRow([arg.name, arg.bio], copyEncoders);
            if (copyRowBatch.length > 0 && copyRowBatch.length + copyRow.length > sqlcCopyFromMaxChunkBytes) {
                await sqlcCopyFromWrite(copyStream, copyStreamState, copyRowBatch);
                copyRowBatch = "";
            }
            copyRowBatch += copyRow;
        }
        await sqlcCopyFromWrite(copyStream, copyStreamState, copyRowBatch);
        await sqlcCopyFromFlushWrites(copyStreamState);
        await sqlcCopyFromEnd(copyStream);
        sqlcCopyFromThrowIfError(copyStreamState);
        return args.length;
    }
    catch (error) {
        copyStream.destroy?.(error);
        throw error;
    }
    finally {
        copyStream.off?.("error", onCopyStreamError) ?? copyStream.removeListener?.("error", onCopyStreamError);
    }
}

export const deleteAuthorQuery = `-- name: DeleteAuthor :exec
DELETE FROM authors
WHERE id = $1`;

export interface DeleteAuthorArgs {
    id: string;
}

export async function deleteAuthor(sql: Sql | TransactionSql, args: DeleteAuthorArgs): Promise<void> {
    await sql.unsafe(deleteAuthorQuery, [args.id]);
}

export const batchCreateAuthorQuery = `-- name: BatchCreateAuthor :batchone
INSERT INTO authors (
  name, bio
) VALUES (
  $1, $2
)
RETURNING id, name, bio`;

export interface BatchCreateAuthorArgs {
    name: string;
    bio: string | null;
}

export interface BatchCreateAuthorRow {
    id: string;
    name: string;
    bio: string | null;
}

export interface BatchCreateAuthorBatchResult {
    index: number;
    row: BatchCreateAuthorRow | null;
}

export async function batchCreateAuthor(sql: Sql, args: BatchCreateAuthorArgs[], options?: SqlcBatchOptions): Promise<BatchCreateAuthorBatchResult[]> {
    const batchSql = await sql.reserve();
    try {
        return await sqlcRunBatched(args, options, async (arg, index): Promise<BatchCreateAuthorBatchResult> => {
            const rows = await batchSql.unsafe(batchCreateAuthorQuery, [arg.name, arg.bio]).values();
            if (rows.length !== 1) {
                return { index, row: null };
            }
            const row = rows[0];
            if (!row) {
                return { index, row: null };
            }
            return {
                index,
                row: {
                    id: row[0],
                    name: row[1],
                    bio: row[2]
                }
            };
        });
    }
    finally {
        batchSql.release();
    }
}

export const batchListAuthorsByBioQuery = `-- name: BatchListAuthorsByBio :batchmany
SELECT id, name, bio FROM authors
WHERE bio = $1
ORDER BY name`;

export interface BatchListAuthorsByBioArgs {
    bio: string | null;
}

export interface BatchListAuthorsByBioRow {
    id: string;
    name: string;
    bio: string | null;
}

export interface BatchListAuthorsByBioBatchResult {
    index: number;
    rows: BatchListAuthorsByBioRow[];
}

export async function batchListAuthorsByBio(sql: Sql, args: BatchListAuthorsByBioArgs[], options?: SqlcBatchOptions): Promise<BatchListAuthorsByBioBatchResult[]> {
    const batchSql = await sql.reserve();
    try {
        return await sqlcRunBatched(args, options, async (arg, index): Promise<BatchListAuthorsByBioBatchResult> => {
            const rows = await batchSql.unsafe(batchListAuthorsByBioQuery, [arg.bio]).values();
            return {
                index,
                rows: rows.map(row => ({
                    id: row[0],
                    name: row[1],
                    bio: row[2]
                }))
            };
        });
    }
    finally {
        batchSql.release();
    }
}

export const batchDeleteAuthorQuery = `-- name: BatchDeleteAuthor :batchexec
DELETE FROM authors
WHERE id = $1`;

export interface BatchDeleteAuthorArgs {
    id: string;
}

export interface BatchDeleteAuthorBatchResult {
    index: number;
}

export async function batchDeleteAuthor(sql: Sql, args: BatchDeleteAuthorArgs[], options?: SqlcBatchOptions): Promise<BatchDeleteAuthorBatchResult[]> {
    const batchSql = await sql.reserve();
    try {
        return await sqlcRunBatched(args, options, async (arg, index): Promise<BatchDeleteAuthorBatchResult> => {
            await batchSql.unsafe(batchDeleteAuthorQuery, [arg.id]);
            return { index };
        });
    }
    finally {
        batchSql.release();
    }
}

