name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: sqlc-dev/setup-sqlc@v4
      with:
        sqlc-version: '1.24.0'
    - uses: actions/setup-node@v4
    - name: Build
      run: |
        make generate
    - uses: actions/upload-artifact@v4
      with:
        name: plugin
        path: examples/plugin.wasm
        overwrite: true
